// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TMS.EF.NTier.DAL.Context;

#nullable disable

namespace TMS.EF.NTier.DAL.Migrations
{
    [DbContext(typeof(TaskManagementSystemDbContext))]
    [Migration("20231021180311_DataSeeding")]
    partial class DataSeeding
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TMS.EF.NTier.DAL.Entities.Issue", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsigneeId")
                        .HasColumnType("int");

                    b.Property<string>("Descritption")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("IssueTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectColumnId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IssueTypeId");

                    b.HasIndex("ProjectColumnId");

                    b.ToTable("Issues");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AsigneeId = 1007,
                            Descritption = "Error et ex blanditiis quod libero.",
                            IssueTypeId = 3,
                            Name = "alias",
                            ProjectColumnId = 4
                        },
                        new
                        {
                            Id = 2,
                            AsigneeId = 1007,
                            Descritption = "Recusandae reiciendis voluptatum reprehenderit aspernatur alias voluptates laborum mollitia.",
                            IssueTypeId = 7,
                            Name = "sed",
                            ProjectColumnId = 10
                        },
                        new
                        {
                            Id = 3,
                            AsigneeId = 1,
                            Descritption = "A exercitationem tempore voluptatem architecto quidem.",
                            IssueTypeId = 10,
                            Name = "qui",
                            ProjectColumnId = 2
                        },
                        new
                        {
                            Id = 4,
                            AsigneeId = 1,
                            Descritption = "Dolorum saepe eos voluptatibus.",
                            IssueTypeId = 8,
                            Name = "non",
                            ProjectColumnId = 2
                        },
                        new
                        {
                            Id = 5,
                            AsigneeId = 2,
                            Descritption = "Molestias adipisci quia vel sint labore.",
                            IssueTypeId = 4,
                            Name = "odio",
                            ProjectColumnId = 9
                        },
                        new
                        {
                            Id = 6,
                            AsigneeId = 1015,
                            Descritption = "Dicta sed maiores repellendus quis expedita aliquam blanditiis similique distinctio.",
                            IssueTypeId = 8,
                            Name = "dignissimos",
                            ProjectColumnId = 1
                        },
                        new
                        {
                            Id = 7,
                            AsigneeId = 1015,
                            Descritption = "Odit quae et blanditiis dolorem excepturi.",
                            IssueTypeId = 5,
                            Name = "ratione",
                            ProjectColumnId = 2
                        },
                        new
                        {
                            Id = 8,
                            AsigneeId = 1007,
                            Descritption = "Vero molestias fugiat dolor quod excepturi maxime et nesciunt vitae.",
                            IssueTypeId = 1,
                            Name = "omnis",
                            ProjectColumnId = 10
                        },
                        new
                        {
                            Id = 9,
                            AsigneeId = 1015,
                            Descritption = "Optio officiis quod quos ea autem libero.",
                            IssueTypeId = 2,
                            Name = "atque",
                            ProjectColumnId = 1
                        },
                        new
                        {
                            Id = 10,
                            AsigneeId = 1007,
                            Descritption = "Ad reprehenderit maiores fugit voluptatem voluptatem qui quibusdam placeat dolorum.",
                            IssueTypeId = 10,
                            Name = "placeat",
                            ProjectColumnId = 8
                        });
                });

            modelBuilder.Entity("TMS.EF.NTier.DAL.Entities.IssueType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("IssueTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Neque dolorem corporis accusantium sequi quibusdam id qui. Aut ut sed omnis et odit. Quisquam qui culpa quis voluptatem et et iusto consequatur adipisci. Eum doloribus quas. Et qui vitae praesentium sint suscipit provident et.",
                            Name = "inventore",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 2,
                            Description = "A non rerum magnam rerum. Odio nemo et deleniti. Consequatur exercitationem aut accusamus eius.",
                            Name = "sint",
                            ProjectId = 12
                        },
                        new
                        {
                            Id = 3,
                            Description = "Debitis ipsam dolore facere optio laudantium. Et amet laboriosam ex. Illo cupiditate odit et molestiae. Dolores deserunt omnis velit nesciunt quia consectetur quo neque illum. Ipsam quis dignissimos qui aut laudantium. Minima dolores iste quam quae repellendus sed neque.",
                            Name = "omnis",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 4,
                            Description = "Asperiores sapiente nostrum perferendis facilis sit pariatur soluta sequi. Natus voluptatibus ullam. Sit officiis illo voluptates tempora dolore. Laudantium et autem.",
                            Name = "saepe",
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 5,
                            Description = "Beatae repellat quae exercitationem in reprehenderit qui molestias voluptatem. Quibusdam sapiente tenetur dolor corrupti. Sunt in quia libero. Dolore aut numquam libero et impedit non. Dolores fuga recusandae quidem vitae.",
                            Name = "quo",
                            ProjectId = 5
                        },
                        new
                        {
                            Id = 6,
                            Description = "Culpa voluptates omnis cum pariatur. Aut voluptatem nostrum minima reiciendis nihil modi vel officia. Neque fugiat necessitatibus fugiat et suscipit soluta exercitationem quia cupiditate.",
                            Name = "nesciunt",
                            ProjectId = 5
                        },
                        new
                        {
                            Id = 7,
                            Description = "Dolor voluptas quia nemo asperiores non sed molestiae in. Odit ea est et omnis. Ad consequatur nisi possimus et assumenda enim velit quidem et. Quaerat quas quia magni.",
                            Name = "et",
                            ProjectId = 2
                        },
                        new
                        {
                            Id = 8,
                            Description = "Est dolore sint. Autem omnis ut iusto natus qui tempora error magnam. Voluptatem magnam voluptas occaecati similique hic velit inventore. Libero placeat maiores vero nihil architecto velit vero laudantium aliquid.",
                            Name = "itaque",
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 9,
                            Description = "Doloribus delectus repellat nobis suscipit. Rem velit soluta reiciendis sint labore architecto nostrum. Quis rem est officia ut dolore quasi reprehenderit. Vel ea commodi accusamus omnis non sint voluptas mollitia saepe. Omnis sunt voluptatem architecto ut molestias quaerat et consequatur.",
                            Name = "ut",
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 10,
                            Description = "Magni explicabo aut rerum enim qui aut sint sunt explicabo. Aut ut animi est rem inventore cum rerum sit. Quia quibusdam quia et labore omnis.",
                            Name = "sit",
                            ProjectId = 12
                        });
                });

            modelBuilder.Entity("TMS.EF.NTier.DAL.Entities.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProjectCategoryId")
                        .HasColumnType("int");

                    b.Property<int>("WorkspaceId")
                        .HasColumnType("int");

                    b.HasKey("Id")
                        .HasName("PK_Project_Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("TMS.EF.NTier.DAL.Entities.ProjectColumn", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ProjectId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectColumns");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "repellat",
                            ProjectId = 5
                        },
                        new
                        {
                            Id = 2,
                            Name = "fuga",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 3,
                            Name = "rerum",
                            ProjectId = 4
                        },
                        new
                        {
                            Id = 4,
                            Name = "in",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "occaecati",
                            ProjectId = 5
                        },
                        new
                        {
                            Id = 6,
                            Name = "est",
                            ProjectId = 12
                        },
                        new
                        {
                            Id = 7,
                            Name = "et",
                            ProjectId = 1
                        },
                        new
                        {
                            Id = 8,
                            Name = "accusantium",
                            ProjectId = 8
                        },
                        new
                        {
                            Id = 9,
                            Name = "nisi",
                            ProjectId = 3
                        },
                        new
                        {
                            Id = 10,
                            Name = "accusantium",
                            ProjectId = 1
                        });
                });

            modelBuilder.Entity("TMS.EF.NTier.DAL.Entities.Issue", b =>
                {
                    b.HasOne("TMS.EF.NTier.DAL.Entities.IssueType", "IssueType")
                        .WithMany("Issues")
                        .HasForeignKey("IssueTypeId")
                        .IsRequired()
                        .HasConstraintName("FK_Issues_To_IssueTypes");

                    b.HasOne("TMS.EF.NTier.DAL.Entities.ProjectColumn", "ProjectColumn")
                        .WithMany("Issues")
                        .HasForeignKey("ProjectColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_Issues_To_ProjectColumns");

                    b.Navigation("IssueType");

                    b.Navigation("ProjectColumn");
                });

            modelBuilder.Entity("TMS.EF.NTier.DAL.Entities.IssueType", b =>
                {
                    b.HasOne("TMS.EF.NTier.DAL.Entities.Project", "Project")
                        .WithMany("IssueTypes")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_IssueTypes_To_Projects");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TMS.EF.NTier.DAL.Entities.ProjectColumn", b =>
                {
                    b.HasOne("TMS.EF.NTier.DAL.Entities.Project", "Project")
                        .WithMany("ProjectColumns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("FK_ProjectColumns_To_Projects");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("TMS.EF.NTier.DAL.Entities.IssueType", b =>
                {
                    b.Navigation("Issues");
                });

            modelBuilder.Entity("TMS.EF.NTier.DAL.Entities.Project", b =>
                {
                    b.Navigation("IssueTypes");

                    b.Navigation("ProjectColumns");
                });

            modelBuilder.Entity("TMS.EF.NTier.DAL.Entities.ProjectColumn", b =>
                {
                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
